### ISSUE TITLE
ubuntu 18.04 를 설치 해보자

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [rkdgusrnrlrl/what-to-do#12]
### 목적
- 우분투 릴리즈 파티(?) 를 보고 18.04 의 설치 의욕 상승중
- 현재 한영 전환 문제를 겪고 있는데 해결 되지 않을까 하는 기대

### 작업 내용
- 우분투 18.04 설치!!!
- 기타 언어, 프로그램, 개발툴 설치
- 우분투 셋업 레파지토리에 추가 된 내용 작성

**Comment by ChangJoo-Park** [comment]
어제 linux mint를 설치했는데 뭔가 신기하네요 ㅋㅋ

https://www.youtube.com/watch?v=YQP3OJ4qvD0

저는 ibus-hangul로 해결했어요

**Comment by rkdgusrnrlrl** [comment]
@ChangJoo-Park 고맙습니다 (_ _) ㅎㅎ ibus 는 jetbrain 계열 IDE 에서 잘 안되더라구요 ㅠㅠ 어제 릴리즈 파티(?) 에 가보니 한국어 지원은 단순 OS 에 문제는 아니고 어플리케이션 과 복합적인 문제가 해결이 쉽지 않다고 하더라구요. 결국 스스로 해결 하는게 답인듯... ㅠㅠ

**Comment by ChangJoo-Park** [comment]
ㅠ_ㅠ

**Comment by rkdgusrnrlrl** [comment]
우선 당장 급하지 않아 보류....언제 하지 ㅠㅠㅠ

**Comment by rkdgusrnrlrl** [comment]
18.10 이 나오면 설치하려고 보류 했는데 산듯한(?) 기분으로 설치 완료~ ㅎㅎ
