### ISSUE TITLE
callback 이 어떻게 promise 로 바뀌는 지 설명 자료 준비 하기

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [rkdgusrnrlrl/what-to-do#4]
## 목적
- callback 소스가 어떻게 promise 로 바뀌고 또 어떻게 await 로 바뀌는 지 보여줌
- 또한 각각이 어떻게 구현 되어있는 지 설정

## 작업 내역
- [x] [callback 서버, promise 서버, async 서버를 만들어봄](https://github.com/rkdgusrnrlrl/callbackToPromis)

**Comment by devjin0617** [comment]
발표하시나요!?

**Comment by rkdgusrnrlrl** [comment]
@devjin0617  발표는 아니고 민호님이 잘 모르겠다고 하셔서 ㅠㅠ ㅎㅎ 말로 하는 것 보다 코드가 있으면 낫지 않을까해서 준비 중입니다.

**Comment by ChangJoo-Park** [comment]
민호님 드디어 오셨나요

**Comment by rkdgusrnrlrl** [comment]
3월 중순 쯤에야 오실 수 있다고 합니다. ㅠㅠ 요즘은 화요일만 오세요. 알려 드릴 수 있는 것 정리해서 알려 드리고 있습니다. ㅎㅎ

**Comment by rkdgusrnrlrl** [comment]
민호님에게 설명 완료 ~ 클로즈

**Comment by ChangJoo-Park** [comment]
초고수네요 현구님 (_ _)

**Comment by rkdgusrnrlrl** [comment]
@ChangJoo-Park  초고수는 무슨요 ㅠㅠ 다행히 민호님 잘 이해해 주셔서 나름 보람을 많이 느꼈습니다. ㅎㅎ 나중에 가르침을 받으로 가겠습니다. ㅎㅎ 창주님 청진님 덕분에 올해 부터 깃헙 열심히 하게 된 것 같아요 :wink:

**Comment by devjin0617** [comment]
아, ㅠㅠ 못돌아오신거군요 ㅠㅠ
