### ISSUE TITLE
celery 배워 보기

### ISSUE THREAD

**Issue by rkdgusrnrlrl** [rkdgusrnrlrl/what-to-do#9]
## 목적
- API 모니터링시 계속 해당 API 를 호출 할 Worker 가 필요 한데 해당 라이브러리 중 celery 가 유명

## 작업내역
- celery 에 있는 예제를 실습해봄
- requests 를 활용 하여 주기적으로 API 를 호출 하고 응답값을 기록

**Comment by rkdgusrnrlrl** [comment]
- [rkdgusrnrlrl/celery_tutorial](https://github.com/rkdgusrnrlrl/celery_tutorial) 레포를 통해 작업 예정

**Comment by ChangJoo-Park** [comment]
좋은게 있네요

**Comment by rkdgusrnrlrl** [comment]
@ChangJoo-Park 생각보다 단순해서 get start 좀 해봤는데.... 일(task) 함수를 만들었느데 에러를 품어내서, 다음으로 나아 갈 수가 없습니다 ㅠㅠ 그리고 어떻게 써야 할지도 고민 중입니다. 

큐같은게 있어서 워커들이 큐에서 일을 가져 가는 구조 인 것 같은데, 1분 주기로 API 를 콜 해야 할 때 어떻게 해야 워커를 효율적으로 운영 할 수 있을 지 고민 중입니다....만 아몰랑 우선 만들자 마이드이긴 합니다. ㅋㅋㅋ

**Comment by ChangJoo-Park** [comment]
(어려운말같습니다)

**Comment by ChangJoo-Park** [comment]
https://www.npmjs.com/package/express-status-monitor

이거 혹시 제가 알려드린적 있나요

**Comment by rkdgusrnrlrl** [comment]
@ChangJoo-Park  없습니다....왜 이제 알려주시나요 ㅋㅋㅋ 감사합니다. 잘 살펴 보겠습니다. ㅎㅎ

**Comment by ChangJoo-Park** [comment]
이럴수가..
보시면 살짝 놀라실수도요 :)

**Comment by boraJeon** [comment]
그렇군요

**Comment by boraJeon** [comment]
저도 열심히 배워보겠습니다 ^^

**Comment by rkdgusrnrlrl** [comment]
@ChangJoo-Park 어떤 의미로 놀랄 수 있는건가요....놀라긴 했지만 의도하신(?) 놀람이 아닐지도 핫핫;;

@boraJeon 저는 열심히 지켜 보겠습니다 ㅎㅎ

**Comment by rkdgusrnrlrl** [comment]
[rkdgusrnrlrl/celery_tutorial](https://github.com/rkdgusrnrlrl/celery_tutorial) 
- 그랩 로그인 API 30 초마다 콜하고 응답과 응답시간을 저장하는 워커 생성 해봄(힘들었다 ㅠㅠ)
- 잘 동작함 
- 다만 redis  로 결과 값을 쌓는데, 알아 보기 힘듬 값이 쌓임
- backend 로 mongo 로 변경 필요 할 듯

**Comment by rkdgusrnrlrl** [comment]
- 생각처럼 잘 동작 하지 않은 예전에 interval 이 정해진 시간아니라 계속(밀리초단위로) 도는 것을 결국 해결 할 수 없어 다른 task schuler 를 찾음
- [agenda/agenda](https://github.com/agenda/agenda) 를 사용 예정 다행히 몽고 DB 기반이라 어려움이 없을 것 같다.
